services:
  v2ray:
    image: v2fly/v2fly-core:v5.16.1
    ports:
      - 443:443/tcp
      - 2007:2007/udp
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./tls:/etc/v2ray/tls
    command: run -c /etc/v2ray/config.json
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 3
